services:
  jellysterr:
    container_name: jellysterr
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_LANGUAGE: ${APP_LANGUAGE:-fr}
    environment:
      - JELLYFIN_URL=${JELLYFIN_URL}
      - APP_LANGUAGE=${APP_LANGUAGE}
      - TMDB_API_KEY=${TMDB_API_KEY}
    ports:
      - "3000:80"
